// CoronaAction
const STATE_WISE_INIT = 'STATE_WISE_INIT';
const STATE_WISE_SUCCESS = 'STATE_WISE_SUCCESS';
const STATE_WISE_ERROR = 'STATE_WISE_ERROR';

const RESIONAL_CONTACT_INIT = 'RESIONAL_CONTACT_INIT';
const RESIONAL_CONTACT_SUCCESS = 'RESIONAL_CONTACT_SUCCESS';
const RESIONAL_CONTACT_ERROR = 'RESIONAL_CONTACT_ERROR';

const WORLD_CASES_INIT = 'WORLD_CASES_INIT';
const WORLD_CASES_SUCCESS = 'WORLD_CASES_SUCCESS';
const WORLD_CASES_ERROR = 'WORLD_CASES_ERROR';

const NEWS_NOTIFICATION_INIT = 'NEWS_NOTIFICATION_INIT';
const NEWS_NOTIFICATION_SUCCESS = 'NEWS_NOTIFICATION_SUCCESS';
const NEWS_NOTIFICATION_ERROR = 'NEWS_NOTIFICATION_ERROR';

const TEST_CENTER_INIT = 'TEST_CENTER_INIT';
const TEST_CENTER_SUCCESS = 'TEST_CENTER_SUCCESS';
const TEST_CENTER_ERROR = 'TEST_CENTER_ERROR';

export {
  // CoronaAction
  STATE_WISE_INIT,
  STATE_WISE_SUCCESS,
  STATE_WISE_ERROR,
  RESIONAL_CONTACT_INIT,
  RESIONAL_CONTACT_SUCCESS,
  RESIONAL_CONTACT_ERROR,
  WORLD_CASES_INIT,
  WORLD_CASES_SUCCESS,
  WORLD_CASES_ERROR,
  NEWS_NOTIFICATION_INIT,
  NEWS_NOTIFICATION_SUCCESS,
  NEWS_NOTIFICATION_ERROR,
  TEST_CENTER_INIT,
  TEST_CENTER_SUCCESS,
  TEST_CENTER_ERROR,
};
