// Authentication
const CONTACT_US_INIT = 'CONTACT_US_INIT';
const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
const CONTACT_US_ERROR = 'CONTACT_US_ERROR';

const DAILY_STATS_INIT = 'DAILY_STATS_INIT';
const DAILY_STATS_SUCCESS = 'DAILY_STATS_SUCCESS';
const DAILY_STATS_ERROR = 'DAILY_STATS_ERROR';

export {
  // Authentication
  CONTACT_US_INIT,
  CONTACT_US_SUCCESS,
  CONTACT_US_ERROR,
  DAILY_STATS_INIT,
  DAILY_STATS_SUCCESS,
  DAILY_STATS_ERROR,
};
